# Generated by Django 4.2.4 on 2023-10-03 04:45

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatars/base_avatar.png', upload_to=main_app.models.avatar_file_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main_app.models.photo_file_path),
        ),
    ]
