# Generated by Django 4.2.4 on 2023-09-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='main_app/static/photo/base_avatar.png',
                                    upload_to='main_app/static/photo/'),
        ),
    ]
