# Generated by Django 4.2.4 on 2023-09-29 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 29, 8, 39, 36, 160623), verbose_name='pubdate'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 29, 8, 39, 36, 157625), verbose_name='pubdate'),
        ),
    ]
