# Generated by Django 4.2.4 on 2023-09-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='media/static/photo/base_avatar.png', upload_to='media/static/photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='media/static/photo/base_avatar.png', upload_to='media/static/photo'),
        ),
    ]
