# Generated by Django 4.2.4 on 2023-09-19 08:44

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_post_id_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 19, 11, 44, 27, 65626), verbose_name='pubdate'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Enter tags separated by commas', max_length=50, primary_key=True, serialize=False),
        ),
    ]
