# Generated by Django 4.2.4 on 2023-09-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='base_avatar.png', upload_to='avatars/'),
        ),
    ]
