# Generated by Django 4.2.4 on 2023-09-19 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_post_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 19, 17, 25, 43, 934554), verbose_name='pubdate'),
        ),
    ]
