# Generated by Django 4.2.4 on 2023-09-20 07:47

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_post_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 20, 10, 47, 4, 780835), verbose_name='pubdate'),
        ),
    ]
