# Generated by Django 4.2.4 on 2023-09-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photos',
            field=models.ManyToManyField(related_name='posts', to='main_app.photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='main_app.tag'),
        ),
    ]
