# Generated by Django 4.2.4 on 2023-11-14 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0007_alter_subscribe_subscribed_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
