# Generated by Django 4.2.4 on 2023-09-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_photo_image_alter_post_photos_alter_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='author',
        ),
    ]
