# Generated by Django 4.2.4 on 2023-11-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_customuser_my_subscribes_dict_post_dislikes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
