# Generated by Django 4.2.4 on 2023-09-26 08:43

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_post_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 26, 11, 43, 48, 805367), verbose_name='pubdate'),
        ),
    ]
