# Generated by Django 4.2.4 on 2023-09-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_user_id_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='main_app.photo'),
        ),
    ]
