# Generated by Django 4.2.4 on 2023-09-26 08:50

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_post_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 26, 11, 50, 38, 756793), verbose_name='pubdate'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 26, 11, 50, 38, 755789), verbose_name='pubdate'),
        ),
    ]
