# Generated by Django 4.2.4 on 2023-09-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_photo_post_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photos',
        ),
    ]
