# Generated by Django 4.2.4 on 2023-09-15 14:30

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_post_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 15, 17, 30, 26, 785923), verbose_name='pubdate'),
        ),
    ]
